### PR TITLE
solved em10

### PR DESCRIPTION
**Pull request by Gauravtb2253**
Hello
I have solved EM10 pls check

### CODE REVIEW

**Comment by samyakmaitre** [comment]
![Uploading 

I want it to look it like this. promoted label on cards is not required, card background color = html body background color.

**Comment by Gauravtb2253** [comment]
pls check

**Comment by samyakmaitre** [comment]
reduce cards size, arrange cards in single line / 1x5 alignment
add some border radius to images. will merge then.

**Comment by Gauravtb2253** [comment]
I have made changes
Also for the poster in 3rd and 4th image try to keep the dimensions similar to the remaining three so it will look proper

**Comment by Gauravtb2253** [comment]
Hello any updates

**Comment by samyakmaitre** [comment]
Checked

**Comment by samyakmaitre** [comment]
Thank you for your contribution! The merge has been completed successfully, and the labels have been added. I appreciate your efforts, and don't forget to connect with me on GitHub!

Best regards,
Samyak

**Review by samyakmaitre — COMMENTED** [review]
Changes Reviewed

**Comment by shreya-paul-17** [comment]
@sanjay-kv @MastanSayyad please review this

**Review by MastanSayyad — COMMENTED** [review]
Hi @samyakmaitre It has some CSS adjustments and additions with few scripts, it should `level 2`

image

**Pull request merged**
