### PR TITLE
Enhance NavBar Functionality and Header Visibility

### PR DESCRIPTION
**Pull request by MohdAftab011**
### Summary of Changes
- Updated the NavBar component to categorize the services and improve alignment for better user navigation.
- Adjusted the Header to hide when users are on the Login and Sign-Up pages, creating a cleaner interface.
- Fixed the alignment of the "Show" button in the Password input box, ensuring a more polished look.

## Login/SignUp Page
Screenshot 2024-10-06 224248
Screenshot 2024-10-06 224300

## NavBar Component

https://github.com/user-attachments/assets/188782af-4bd9-44d4-9c48-c15edc63acc1

Please tag this with gssoc-ex and hacktoberfest

### CODE REVIEW

**Comment by samyakmaitre** [comment]
deploy failed, resolve conflicts

**Comment by MohdAftab011** [comment]
> deploy failed, resolve conflicts

It seems there is a deployment error. Please give me screenshots of error logs in Vercel.

**Comment by samyakmaitre** [comment]
I have a request you to re work with the latest version, coz there was a major issue resolved.
So please re work on these same issue and create a new PR I will merge it DW.

For now I am closing this PR

**Comment by MohdAftab011** [comment]
> I have a request you to re work with the latest version, coz there was a major issue resolved. So please re work on these same issue and create a new PR I will merge it DW.
> 
> For now I am closing this PR

Thank you for the update! I’ll rework the changes with the latest version and address the issue that was resolved. I’ll create a new PR shortly. Appreciate you closing this one for now!

**Pull request closed without merging**
