### PR TITLE
Header-Navbar Sticky 

### PR DESCRIPTION
**Pull request by saras-69**
Implements sticky navbar functionality.
Navbar becomes sticky after scrolling past the first 10vh of the webpage.

### CODE REVIEW

**Comment by saras-69** [comment]
Screenshot 2024-10-13 233215

**Comment by saras-69** [comment]
@samyakmaitre

**Comment by samyakmaitre** [comment]
I will review for changes and merge, kindly wait.

**Comment by samyakmaitre** [comment]
kindly sync your fork and create new PR, will merge

Thank you

**Comment by saras-69** [comment]
@samyakmaitre please look into this https://github.com/samyakmaitre/eventmint/pull/372

**Pull request closed without merging**
