### PR TITLE
fix NavBar & Header

### PR DESCRIPTION
**Pull request by saras-69**
Description
This PR adjusts the height of the NavBar & Header components to ensure a consistent and responsive layout using 10vh. It resolves any overlapping issues and improves the scrolling experience.

Related Issues
Closes : https://github.com/samyakmaitre/eventmint/pull/281#issuecomment-2415682353

Before:

https://github.com/user-attachments/assets/ac5b8fdc-b4d3-454b-b2ee-ef7054d03902

And Logo was not fix and header and navbar component get scroll

After:

https://github.com/user-attachments/assets/5bd73d90-a6fa-4f17-aa23-743cd931e6ce

Additional Context
This fix improves the header and navbar behavior across devices by using 10vh to maintain responsiveness and prevent UI shifts during scrolling.

### CODE REVIEW

**Comment by samyakmaitre** [comment]
scroll is not smooth.

**Comment by saras-69** [comment]
> scroll is not smooth.

Because there is two different components if want smooth I'll  fix this

**Comment by samyakmaitre** [comment]
yes please

**Comment by saras-69** [comment]
> > scroll is not smooth.
> 
> Because there is two different components if want smooth I'll fix this

It will become smooth when I change 10vh to 100 vh

**Comment by saras-69** [comment]
> yes please

Can please add level3 in my previous pr for pasword recovery page🥹

**Comment by samyakmaitre** [comment]
Was it able to send mail for recovery?

**Comment by saras-69** [comment]
> Was it able to send mail for recovery
No, for that You have to set up an SMTP server (like Gmail SMTP, SendGrid, or Nodemailer in Node.js)

**Comment by saras-69** [comment]
For that I will create seprate issue

**Comment by samyakmaitre** [comment]
Thats why, you have more labels from my side right.....and more incoming too

**Comment by saras-69** [comment]
> Thats why, you have more labels from my side right.....and more incoming too

Okay 😊

**Review by samyakmaitre — COMMENTED** [review]
Code Reviewed

**Review by samyakmaitre — COMMENTED** [review]
Reminder,
Scroll not smooth
also resolve conflicts

**Comment by samyakmaitre** [comment]
issue resolved by another PR

**Pull request closed without merging**
