### PR TITLE
#EM1 navbar is updated

### PR DESCRIPTION
**Pull request by jeevika17**
The hover line for the navbar is fixed

### CODE REVIEW

**Comment by samyakmaitre** [comment]
image
Not showing under movie option.

**Comment by samyakmaitre** [comment]
also sync your fork

**Comment by jeevika17** [comment]
check now

**Comment by samyakmaitre** [comment]
Hi there,

Thank you for your interest! The issue has already been assigned to another contributor since I did notget any response from your side. We appreciate your eagerness to help and look forward to your contributions in the future. Dont forget to connect on Github....

Best regards,
Samyak

**Review by samyakmaitre — COMMENTED** [review]
Changes Reviewed

**Pull request closed without merging**
