### PR TITLE
Feat: Adding whole logic of login and signup functionality!

### PR DESCRIPTION
**Pull request by harshbhar0629**
Fixes: #24 I'm implemented the whole logic of Login and signup and also done testing in my own PC.
For backend:- I used NodeJs and for database I used MongoDB.

backend
**Folder Structure**
**BACKEND**
**Backend**: It contains the whole backend of login and signup functionality.
**Config**: It connect the node environment to the database with dbConnect() function.
**Controllers**: In controllers there is a auth.js which is related to the authentication with all validation and i also used hashing(Bcrypt package) for to secure the password and also used Json-Web-Token for validation of token. No same user can create an account on this platform via same email address.
**Models**: There is only one model which is User model contains ["Firstname", "Lastname", "Email", "Password", "image-url", "token"].
**.env** file:  In this file there are 3 deafult value you can add or edit accordingly
                    MONGODB_URL = mongodb://127.0.0.1:27017/  **It req database url**
                    JWT_SECRET = "MYSECRET" **Select your token**
                    PORT = 4000 **Enter your port number**
                    
**Index.js**: There is basic setup of express and also used middlewares for parsing data.

**UI**
**Components/Auth** : There are 3 components are there Template.js LoginForm.js, SignupForm.js On the basis of condition I render Login and signupform respectively! There is simple setup for login and signup using tailwindCSS.
**SignupForm** : When user click on create account we call to backend for creating a user and also show toast for interactive UI.
**LoginForm** : When user click on Sign in we call to backend for checking this user exist or not and also hashed their password for matching this is same passsword or not.

**Reducer**: We combine all the reducer or slices which is used in login and signup functionality.
**Slices**: We create two slices 1. authSlice which mainly holds token and profileSlice contains the user data for future purpose like for creating a dashboard of user then data will be required so I secured all data for now!.
**Services/operations**: Inside operations there is one file **authAPI** which connects or call the backend from the client side  and send response accordingly, There are 3 main functions are there LOGIN, SIGNUP, LOGOUT, In login and signup we take data from client side and make a call to **apiConnector** to pass the given data and show response accordingly!

**Services/apiConnector.js**: In this file it only recieve the given data from client side and return an axios instance  with **taking the method of call, data, url, headers, params** 

**Services/api.js**: In this file I'm mentioning the all routes of backend which is used in login and signup functionality!.
 
**App.js**: In App.js I'm creating a home page so every listing and everything lie on Home page and also create a route for login and signup.

**Index.js**: I just wrapped the App component in Provider of react-redux.
**.env**: It having REACT_BASE_URL you can edit acccordingly!

I also setup for tailwindCSS.

Now executable command is changed so Enter: **npm run dev** so that backend and frontend starts immediately! Please remeber the commands:)  and also updates in readme.md file.

**TEST FUNCTIONALITY**
https://github.com/user-attachments/assets/a67d93c2-1690-42e1-b6ed-aafcba61053c

@samyakmaitre Please review my PR and merge accordingly! Thanks for viewing..

### CODE REVIEW

**Comment by harshbhar0629** [comment]
For Deployment please edit the .env file paths because I used localhost path and also edit the mongo_url because I used localhost mongo_url you can edit the url!

**Comment by samyakmaitre** [comment]
can you please make single button for Login/Signup. Please make the changes and let me know.

**Comment by harshbhar0629** [comment]
Ok i will create a single button!

**Comment by harshbhar0629** [comment]
Now editing done please @samyakmaitre  review my PR again!

Check Please:
https://github.com/user-attachments/assets/6e59fc21-f5d4-4175-89a7-03a2bac1311a

**Comment by samyakmaitre** [comment]
One last change:
Color theme limited to red, black and white.

**Comment by harshbhar0629** [comment]
Ok, but i want to ask is this project is not part of hactoberfest?? Because when i create a PR then it will show me not participating tag @samyakmaitre

**Comment by samyakmaitre** [comment]
The project is labelled under hacktoberfest topic kindly check description. Also labels are not yet added for this pull request, once the final task is done, I will add them, DW.

Feel free to ask!

**Comment by harshbhar0629** [comment]
@samyakmaitre  Please now review Color theme edit according to your instructions.

**Comment by harshbhar0629** [comment]
@samyakmaitre  Please review again, According to your given color I Edit page accordingly!!

Test Color: 

https://github.com/user-attachments/assets/417db910-5d42-4f92-8a23-09896235ef3e

**Pull request merged**
