### PR TITLE
Integrated  Firebase Authentication

### PR DESCRIPTION
**Pull request by Nkovaturient**
### Issue :  #3 

event1

event5

1)Implemented the following authentication methods:-

- Signup
event2

- Login
event3

- GoogleAuth

2)Alongside, enhanced code modularity and assets as well as styling for better retrieval of data as and when required

3)Sticky Header and enhanced Footer styling + improved UI/UX for seamless user experience

event4

### CODE REVIEW

**Comment by samyakmaitre** [comment]
I need a preview of it first, then we'll move forward.

**Comment by Nkovaturient** [comment]
> I need a preview of it first, then we'll move forward.

Sure, I will present you with a demo video.

**Comment by Nkovaturient** [comment]
> I need a preview of it first, then we'll move forward.

Hello @samyakmaitre , 

Here is a demo video on seamlessly integrated Auth Setup via firebase— Signup, Login, GoogleAuth methods:-

https://github.com/user-attachments/assets/3847e1a3-d21b-40a4-b074-b180f65c3ec0

**Comment by Nkovaturient** [comment]
> > I need a preview of it first, then we'll move forward.
> 
> Hello @samyakmaitre , 
> 
> Here is a demo video on seamlessly integrated Auth Setup via firebase— Signup, Login, GoogleAuth methods alongwith enhanced UI/UX integration:-
> 
> https://github.com/user-attachments/assets/3847e1a3-d21b-40a4-b074-b180f65c3ec0
> 
> 
> 
>

**Comment by Nkovaturient** [comment]
Also, I would like to follow your advice on backend setup and search functionality, data configuration implementation.
Can you guide me on how to achieve it (like extra feature, or as such) as an apt setup for our eventmint web app?!

**Comment by samyakmaitre** [comment]
As of now only keep the signup/login authentication , remove the black theme change. I will merge it.

**Comment by Nkovaturient** [comment]
> As of now only keep the signup/login authentication , remove the black theme change. I will merge it.

Hey there @samyakmaitre , 
Changed and Committed!, ✅

Screenshot (237)

**Comment by samyakmaitre** [comment]
I dont want to change the prior appearance, kindly refer to the image for reference. other than this everything is perfect.
image

**Comment by Nkovaturient** [comment]
> I dont want to change the prior appearance, kindly refer to the image for reference. other than this everything is perfect. Ignore bookmyshow name.
> 
> image

Roger that! I will get back to you with update soon! 🚀👨‍💻

**Comment by Nkovaturient** [comment]
Hey there @samyakmaitre ! 
I have accomplished as you desired including navbar, header and footer-theme aligned. 😄🌟 

Screenshot (239)

**Comment by samyakmaitre** [comment]
Kindly unstage footer changes, I just need your signup/login authentication coz footer is handeled by another dedicated contributor.
Thank you for your cooperation, your PR is under lvl3 DW. just make these changes. 
I myself am eager to merge this 🤣

**Comment by Nkovaturient** [comment]
> Kindly unstage footer changes, I just need your signup/login authentication coz footer is handeled by another dedicated contributor. Thank you for your cooperation, your PR is under lvl3 DW. just make these changes. I myself am eager to merge this 🤣

ah! Sure.. 🙂🙂

**Comment by Nkovaturient** [comment]
Kindly resolve this conflicts since I have changed footer in the same commit and havent updated my forked repo with your main repo changes. I am facing reference broken error hence I had to revert to the last commit as of now. 
Holy! 🙂🙏

**Pull request merged**
