### PR TITLE
Add or modify some css properties

### LINKED ISSUE #304: Improve the page of the website
Add more css properties  to make more attractive

Screenshot 2024-10-15 124206

Please assign me the issue @samyakmaitre 
Thank you!!!

### PR DESCRIPTION
**Pull request by Dipanita45**
Update or add some css properties like transition, box shado\w , responsive and etc to make the website more user friendly 

Fixes #304 

Please review my pull request and label me level 2 @samyakmaitre 
Thank you for the chance

### CODE REVIEW

**Comment by samyakmaitre** [comment]
image

movie cards are removed

**Comment by samyakmaitre** [comment]
Thank you for your suggestion. Currently, this is not a priority at the moment. However, feel free to create new issues or suggest additional features for future development.

Looking forward to collaborating again soon.

Best regards,
Samyak

**Comment by Dipanita45** [comment]
Please label me

**Review by samyakmaitre — COMMENTED** [review]
Changes Reviewed

**Comment by Dipanita45** [comment]
Please label

**Comment by Dipanita45** [comment]
On the new pull request

**Pull request closed without merging**
