### PR TITLE
 little styling of eventmint and also build Streamevents 

### PR DESCRIPTION
**Pull request by simran0809**
Little styling of eventmint and also  have build Streamevents

### CODE REVIEW

**Comment by simran0809** [comment]
> 🎉 Thank you for your contribution! Your pull request has been submitted successfully. A maintainer from Eventmint team will review it as soon as possible. We appreciate your support in making this project better

respond please to my PR

**Review by samyakmaitre — COMMENTED** [review]
I will look into it, Kindly wait

**Comment by samyakmaitre** [comment]
Thank you for the updates. However, the recent changes appear to be non-essential and don’t contribute significantly to the project’s functionality or user experience.

Regards,
Samyak

**Comment by simran0809** [comment]
but i have given my effort to design stream event screen page so please give some rewards and levels for gssoc leaderboard

**Pull request closed without merging**
