### PR TITLE
Fixed footer details and added a back to top button 

### LINKED ISSUE #20: Improve footer

### LINKED ISSUE #33: Add "Back to Top" button
I would like to add a scroll to top button that allows users to quickly return to the top of the page with a single click. 
This will help your website look more modern.
@samyakmaitre Could you please assign me this issue under gssoc'24 extended and hacktoberfest-accepted?

### LINKED ISSUE #35: Improve Footer and Navbar Sections
I'd like to improvements to both the Footer and Navbar sections to enhance usability and design consistency across the site.

Could you please add the "label for level" , "Hacktoberfest-accepted" label and "gssoc-ext" label to the issue .

This will ensure my contributions are counted towards Hacktoberfest.

Screenshot 2024-10-03 113936

Screenshot 2024-10-03 113954

### LINKED ISSUE #40: Add Footer and Enhance UI
I Finish or Resolve this issue as soon as possible,
With better UI Enhancements ,
Asap

### LINKED ISSUE #43: add "scroll to top" button
1-Implement a "Scroll to Top" button that appears when users scroll down the page.
2-Ensure the button is easily visible and matches the website's design.
3-Make the button functional, allowing smooth scrolling back to the top of the page when clicked.
please assign this task to me

### PR DESCRIPTION
**Pull request by PraveenUppar**
Fixed footer details and added a back to top button 
 
Fixes #40 
Fixes #43
Fixes #33
Fixes #20
Fixes #35 

##Screenshot
Screenshot 2024-10-04 115331

### CODE REVIEW

**Comment by PraveenUppar** [comment]
The code has no conflicts with the base branch

**Comment by PraveenUppar** [comment]
I checked with running the file no issues were found

**Comment by PraveenUppar** [comment]
Once merge with the main branch and check 
Can you gssoc-ext and hacktoberfest-accepeted label to the pr it would really help me
Thankyou

**Comment by samyakmaitre** [comment]
Make headings bolder and try adding underline hover effect.

**Pull request closed without merging**
