### PR TITLE
Added Footer 

### PR DESCRIPTION
**Pull request by Mujtabaa07**
Added Footer with icons animations ,

issue number: #40

https://github.com/user-attachments/assets/4eac1fb2-90a1-4f14-8df4-9fa307b4167f

### CODE REVIEW

**Comment by samyakmaitre** [comment]
Kindly add a "Back to Top Button" in footer and 2-3 columns at place of discover, help. kindly refer image.
image

**Comment by Mujtabaa07** [comment]
> Kindly add a "Back to Top Button" in footer and 2-3 columns at place of discover, help. kindly refer image. image

Yes Sure i'll Add it asap

**Comment by samyakmaitre** [comment]
> > Kindly add a "Back to Top Button" in footer and 2-3 columns at place of discover, help. kindly refer image. image
> 
> Yes Sure i'll Add it asap

Kindly work on this.

**Comment by Mujtabaa07** [comment]
> > > Kindly add a "Back to Top Button" in footer and 2-3 columns at place of discover, help. kindly refer image. image
> > 
> > 
> > Yes Sure i'll Add it asap
> 
> Please work on this.

added/resolved in issue #71

https://github.com/user-attachments/assets/7a468c99-ed79-48b4-aaf5-835087e9b29e

**Comment by samyakmaitre** [comment]
Untitled
Kindly align columns this way

**Comment by Mujtabaa07** [comment]
> Untitled Kindly align columns this way

Now 

https://github.com/user-attachments/assets/b59be6e6-aecd-4174-94e3-bc3e6e7e75cc
added/resolved in issue: #71

**Comment by Mujtabaa07** [comment]
resolved conflicts done

**Pull request merged**
