### PR TITLE
header fixed while scrolling 

### PR DESCRIPTION
**Pull request by riyaaryan2004**
Reference issue  #9 
issue assigned to me is fixed..
header is fixed while scrolling for smooth user experience.
Screenshot 2024-10-04 172838

Screenshot 2024-10-04 172911

### CODE REVIEW

**Comment by samyakmaitre** [comment]
Just a small change, please add bottom shadow to the static navbar you worked on.

**Comment by riyaaryan2004** [comment]
okay @samyakmaitre i will add

**Comment by riyaaryan2004** [comment]
shadow added 
Screenshot 2024-10-04 194043

**Comment by samyakmaitre** [comment]
No further changes are needed at this time. Feel free to collaborate on additional features in the future. Please do not create Pull Request until I confirm in the issue section/or changes are completed, to avoid confusion.

Thank you for your cooperation.

**Comment by riyaaryan2004** [comment]
@samyakmaitre okay!

**Comment by riyaaryan2004** [comment]
@samyakmaitre 
can u add lable of gssoc-ext

**Comment by samyakmaitre** [comment]
> @samyakmaitre can u add lable of gssoc-ext

I missed to add.
Labelled gssoc-ext...

**Comment by riyaaryan2004** [comment]
@samyakmaitre my name is not in assignee section.
Can u please add?

**Pull request merged**
