### PR TITLE
Fixed flex error and Ratings error

### PR DESCRIPTION
**Pull request by SKADE2303**
The flex CSS wasn't working properly on the left-container and the right container in the MovieDetails.js so changed it.
Also updated the Movie ratings error which was mentioned in the issue I created

### CODE REVIEW

**Comment by samyakmaitre** [comment]
sync your fork please

**Comment by SKADE2303** [comment]
synced

**Comment by samyakmaitre** [comment]
Thank you for your contribution! The merge has been completed successfully, and the labels have been added. I appreciate your efforts, and don't forget to connect with me on GitHub!

Best regards,
Samyak

**Review by samyakmaitre — COMMENTED** [review]
Changes Reviewed

**Pull request merged**
