### PR TITLE
Password Recovery Component 

### PR DESCRIPTION
**Pull request by saras-69**
Password Recovery Component for Issue #285 

Adds Password Recovery feature to the login/signup flow.
Users can recover their password via email through a recovery form.
Includes modal for password recovery with smooth transitions.

### CODE REVIEW

**Comment by saras-69** [comment]
@samyakmaitre

**Comment by samyakmaitre** [comment]
I will review for changes and merge, kindly wait.

**Comment by samyakmaitre** [comment]
Please share a demo video

**Comment by samyakmaitre** [comment]
Requesting a response from your side.

**Comment by saras-69** [comment]
> Requesting a response from your side.

I already created the pr

**Comment by samyakmaitre** [comment]
reviewed changes, please sync PR so that I can merge. notify

**Comment by samyakmaitre** [comment]
Thank you for your contribution! The merge has been completed successfully, and the labels have been added. I appreciate your efforts, and don't forget to connect with me on GitHub!

Best regards,
Samyak

**Pull request merged**
