### PR TITLE
Added navigation section in offers Page and list show page

### PR DESCRIPTION
**Pull request by sujeet9682**
### Description
Added Navbar, header and footer to make navigation smoothly in offers Page and list show page and to keep UI Uniformity in application

Screenshot 2024-10-31 at 1 29 20 PM
Screenshot 2024-10-31 at 1 29 28 PM

### CODE REVIEW

**Review by samyakmaitre — COMMENTED** [review]
Code reviewed

**Comment by samyakmaitre** [comment]
Thank you for your contribution! The merge has been completed successfully, and the labels have been added. I appreciate your efforts, and don't forget to connect with me on GitHub!

Best regards,
Samyak

**Comment by sujeet9682** [comment]
Sure. 
I am already in Github connection with you and thanks for being active in assigning and merging contributions in your Repo

**Comment by sujeet9682** [comment]
you are too late in merging PR. Now it wil not be considered for hacktoberfest

**Pull request merged**
