### PR TITLE
changed name as eventmint from bookmyshow

### PR DESCRIPTION
**Pull request by Sameeratweb**
Changed the title of the webpage to "EventMint" from its previous name "BookMyShow".

### CODE REVIEW

**Comment by samyakmaitre** [comment]
Please use logo from src folder instead of text.

**Comment by swaramaitre** [comment]
@samyakmaitre Please assign the task to me. Although the logo has been updated from "BookMyShow" to "EventMint," it still does not fully meet the UX requirements. I will ensure that the logo you provided is integrated and additionally redirect to homepage.

**Comment by samyakmaitre** [comment]
Hi @swaramaitre ,
Thank you for the suggestion! Please go ahead, resolve issue and create a pull request. I will review and cooperate to merge it with the appropriate labels. Dont forget to connect on Github....

Best regards,
Samyak

**Comment by samyakmaitre** [comment]
The issue has been resolved under #153. Thank you for your attention and support.

Best regards,
Samyak Maitre

**Pull request closed without merging**
