### PR TITLE
removed dark mode

### PR DESCRIPTION
**Pull request by Gauravtb2253**
I have removed the dark mode functionality 
Pls check

### CODE REVIEW

**Comment by samyakmaitre** [comment]
image


icon still visible

**Comment by Gauravtb2253** [comment]
check

**Comment by samyakmaitre** [comment]
Thank you for your contribution! The merge has been completed successfully, and the labels have been added. I appreciate your efforts, and don't forget to connect with me on GitHub!

Best regards,
Samyak

**Review by samyakmaitre — COMMENTED** [review]
Changes Reviewed

**Pull request merged**
