### PR TITLE
Movies , Events section and Book movies section implemented, Api for Events section implemented

### PR DESCRIPTION
**Pull request by 30Abhi**
1.Movies page where all available movies are listed with nav bar and search functionality of movie by name. 
2.Event page where all available events using Ticketmaster API are listed with nav bar and search functionality of event by name.
3. Book tickets section provided provides pop up for successful booking of tickets.

Thanks for providing me this amazing opportunity sir . Please check my work and accept it also please provide me appropriate label for GSSoC 2024 Extd (Girls Script Summer of Code).

Very much Delighted.

### CODE REVIEW

**Comment by samyakmaitre** [comment]
Please compare:
Your preview: https://eventmint-dhx2tt8xg-samyakmaitres-projects.vercel.app/
Latest: https://eventmint.vercel.app/

There are many issues I found and therefore cannot merge this PR.

**Comment by 30Abhi** [comment]
Can you tell about the issue so I could fix them 
Your preview: https://eventmint-dhx2tt8xg-samyakmaitres-projects.vercel.app/ --- this is not opening from my side saying I am not part of team

**Comment by samyakmaitre** [comment]
image

**Comment by samyakmaitre** [comment]
Try sync once, I will check it again

**Pull request closed without merging**
