### PR TITLE
[FIXES #EM6] Add SideMenu to the navbar 

### PR DESCRIPTION
**Pull request by Dev-Rishav**
Added a side menu bar for better usability
Solves issue#EM6
Please add the relevant gssoc and hacktoberfest labels. Thank You!

https://github.com/user-attachments/assets/c5413d7f-e2e1-4233-93b1-5201c08d7d03

### CODE REVIEW

**Comment by samyakmaitre** [comment]
please sync your fork

**Comment by samyakmaitre** [comment]
your work is appreciated.

**Comment by Dev-Rishav** [comment]
@samyakmaitre  Fork synced, you can review the changes. Thank You!

**Comment by samyakmaitre** [comment]
bro sync karde firse, leave logo issue

**Comment by samyakmaitre** [comment]
Thank you for your contribution! The merge has been completed successfully, and the labels have been added. I appreciate your efforts, and don't forget to connect with me on GitHub!

Best regards,
Samyak

**Review by samyakmaitre — COMMENTED** [review]
Changes Reviewed

**Pull request merged**
