### PR TITLE
Fix header logo alignment and update footer links

### PR DESCRIPTION
**Pull request by ezDecode**
Closing #186
Hey @samyakmaitre I have created a new PR,
This pull request includes changes to the `Header.css` and `Footer.js` files to improve code readability and maintainability. The changes mainly involve formatting adjustments and minor code improvements.

### CSS Formatting Improvements:

* [`src/assets/styles/Header.css`](diffhunk://#diff-e0204e642b740b914bba05b49faee456047bf4c856b91d4ea990725c52d0d314L26-R46): Reformatted CSS properties for better readability, including aligning comments and properties. [[1]](diffhunk://#diff-e0204e642b740b914bba05b49faee456047bf4c856b91d4ea990725c52d0d314L26-R46) [[2]](diffhunk://#diff-e0204e642b740b914bba05b49faee456047bf4c856b91d4ea990725c52d0d314L123-R141) [[3]](diffhunk://#diff-e0204e642b740b914bba05b49faee456047bf4c856b91d4ea990725c52d0d314L149-L156)

### JavaScript Improvements:

* [`src/components/Footer.js`](diffhunk://#diff-bbc61c7a463361cf5c362945de11c994e0f9d8d0355858d6c0323432bdba3053L71-R71): Replaced `window.pageYOffset` with `window.scrollY` for better readability and consistency.
* [`src/components/Footer.js`](diffhunk://#diff-bbc61c7a463361cf5c362945de11c994e0f9d8d0355858d6c0323432bdba3053L122-R155): Added `no-underline` and `text-left` classes to links for better visual consistency and alignment. [[1]](diffhunk://#diff-bbc61c7a463361cf5c362945de11c994e0f9d8d0355858d6c0323432bdba3053L122-R155) [[2]](diffhunk://#diff-bbc61c7a463361cf5c362945de11c994e0f9d8d0355858d6c0323432bdba3053L208-R209)

### CODE REVIEW

**Comment by ezDecode** [comment]
Hey, @samyakmaitre Kindly, check this and merge it.

**Comment by ezDecode** [comment]
Consider adding some labels to it.

**Comment by samyakmaitre** [comment]
confirm sync.

**Comment by ezDecode** [comment]
Yes, we can merge it, its the updated one @samyakmaitre 
And consider adding a level to it!!

**Comment by samyakmaitre** [comment]
What changes you make tell me

**Comment by ezDecode** [comment]
@samyakmaitre  
**Small changes like removed the underlines from the footer and fixed the dark-mode toggle button position**

**Comment by samyakmaitre** [comment]
image

I can see only this change which is not needed. Is there any other visible change you have made please let me know.

**Comment by ezDecode** [comment]
As a beginner, I don't have proper knowledge but made some changes//
removed footer section links underlines

**Comment by samyakmaitre** [comment]
Alright, do one thing, create another blank PR coz this PR will create if I merge, I will label in new PR.
I hope this is fine.

**Comment by ezDecode** [comment]
How can I do this i have to make the same changes again?? then push again?? @samyakmaitre

**Comment by samyakmaitre** [comment]
un fork, refork, add a space in any code nothing else, create PR.

**Pull request closed without merging**
