### PR TITLE
CSS Styling Contest

### PR DESCRIPTION
**Pull request by yr1404**
#361 

Let me know if any modifications are needed.

### CODE REVIEW

**Comment by yr1404** [comment]
image
image

**Review by samyakmaitre — COMMENTED** [review]
I will look into it, Kindly wait

**Comment by samyakmaitre** [comment]
Kindly sync your to merge

**Comment by yr1404** [comment]
Done

**Comment by samyakmaitre** [comment]
Thank you for your contribution! The merge has been completed successfully, and the labels have been added. I appreciate your efforts, and don't forget to connect with me on GitHub!

Best regards,
Samyak

**Pull request merged**
