### PR TITLE
Add feature: UI improvement and carousal at end , set margins and all too

### PR DESCRIPTION
**Pull request by vanshika704**
Added a heading , set the margins and improved ui 

https://github.com/user-attachments/assets/f6dccfa9-01da-4f37-aa62-d1313eb6e0c9

### CODE REVIEW

**Comment by samyakmaitre** [comment]
image
Please work on these gap, make it continuous flow.

**Comment by samyakmaitre** [comment]
image

Please update the following section of the webpage:

Remove the statement "Book Now, Skip the Line, Vibe Later!"
Replace it with a navigation bar that is missing from this location.
Refer to the next image for guidance on how the navbar should look, and use it as a reference to implement the navbar in the current section.

**Comment by samyakmaitre** [comment]
image

**Comment by vanshika704** [comment]
okay , have worked upon the carousal , you can check

**Comment by samyakmaitre** [comment]
WhatsApp Image 2024-10-08 at 23 06 37_34c2655e


A final change, I will merge
try removing these spaces

**Comment by vanshika704** [comment]
have added the changes 
image
you can check

**Comment by samyakmaitre** [comment]
Thank you for your contribution! The merge has been completed successfully, and the labels have been added. I appreciate your efforts, and don't forget to connect with me on GitHub!

Best regards,
Samyak

**Pull request merged**
