### PR TITLE
Added a movie Page that was missing in application

### PR DESCRIPTION
**Pull request by sujeet9682**
### Description
Added a movie Page in application
Added movie carousel and movies in that page 
Made the route /movies working 

Screenshot 2024-10-31 at 1 28 41 PM

### CODE REVIEW

**Review by samyakmaitre — COMMENTED** [review]
Code reviewed

**Comment by samyakmaitre** [comment]
Thank you for your contribution! The merge has been completed successfully, and the labels have been added. I appreciate your efforts, and don't forget to connect with me on GitHub!

Best regards,
Samyak

**Comment by sujeet9682** [comment]
Wow!!
It is a nice experience to contribute in your repo in the Hacktoberfest. I really enjoyed contributing and it was a great learning experience.

Looking forward to staying connected and hopefully contributing more in the future!

**Comment by sujeet9682** [comment]
you are too late in merging PR. Now it wil not be considered for hacktoberfest

**Pull request merged**
