### PR TITLE
Google Auth

### PR DESCRIPTION
**Pull request by samriddhitiwary**
I have implemented the Google Authorization using Firebase

https://github.com/user-attachments/assets/5bf99ddf-a61e-44f8-afda-1c59442644a3

### CODE REVIEW

**Comment by samriddhitiwary** [comment]
@samyakmaitre I have raised a PR could you please review it

**Comment by samriddhitiwary** [comment]
@samyakmaitre if the code meet you requirements then could you please add the labels in the PR also

**Review by SwanandD121 — COMMENTED** [review]
Good implementation

**Comment by samriddhitiwary** [comment]
@SwanandD121 Thank you, so can this be merged ?

**Comment by samriddhitiwary** [comment]
@samyakmaitre can this be merged?

**Comment by samriddhitiwary** [comment]
@samyakmaitre Thank you soo much

**Pull request merged**
