### PR TITLE
Enhance UI with modern styling: improved header, movie cards, and button hover effects (Hactoberfest)

### LINKED ISSUE #216: updated script for app.css
updated script for app.css Lack of Visual Feedback on Interactive Elements:

The navigation links and buttons lacked modern hover effects like shadows or transitions, which are commonly used for better visual feedback. This can make the UI feel less responsive and interactive.
Flat Design:

The movie cards had very basic styling with a simple border and shadow, but the hover effect was not very noticeable. Modern UIs often use subtle animations, like scaling or shadow changes, to make interactions feel smoother.
Spacing and Alignment:

The spacing between elements (e.g., navigation items, movie cards) was somewhat tight, which could affect readability and visual hierarchy. Modern design usually emphasizes more space between elements for better clarity.
Typography:

The previous font was basic (Arial), which lacked the modern feel that a clean, professional font like Segoe UI or Roboto provides. Typography plays a huge role in enhancing readability and user engagement.
Button Design:

The buttons were functional but lacked a more refined, polished design. They didn’t have smooth color transitions or shadows, which are key to modern web design trends.
Lack of Smooth Transitions:

While there were some hover effects (like changing background colors), the transitions w

### PR DESCRIPTION
**Pull request by akhulisumit**
resolves #216 
Header: Added a shadow effect and improved the hover behavior on navigation items, giving a modern and sleek look. Increased padding for better spacing.
Movie Cards: Implemented a hover scaling effect along with smoother transitions for a more dynamic and interactive user experience. Enhanced spacing with additional padding and margins.
Buttons: Refined the hover effect by adding shadows and a smooth background color transition for better user feedback.
Typography: Updated to a modern, clean font for improved readability and visual appeal. Adjusted font sizes for consistency across the page.
General Styling: Applied minor tweaks to layout, spacing, and color schemes for a more polished and cohesive look.

### CODE REVIEW

**Comment by akhulisumit** [comment]
Hey, can you please review and give updates on my pull request

**Comment by akhulisumit** [comment]
Hello can I get feedback regarding my changes

**Comment by samyakmaitre** [comment]
Kindly sync fork once and let me know.

**Comment by akhulisumit** [comment]
Done, Can you check out now

**Comment by akhulisumit** [comment]
I’ve recently contributed to the repository . Could you please add the gssoc-ext label to my contributions so that they are recognized under the program?

Thank you for your help!

**Comment by samyakmaitre** [comment]
Your preview is still at older version, not much changes found other than values changes and therefore closing this PR.

**Pull request closed without merging**
