### PR TITLE
updated with logo in footer

### PR DESCRIPTION
**Pull request by Sameeratweb**
I've updated the logo in the footer section to match the background.

### CODE REVIEW

**Comment by samyakmaitre** [comment]
replace logo with logo2.png

**Comment by Sameeratweb** [comment]
Screenshot 2024-10-13 154239
This one Right? ive used logo2 itself .Please let me know if anything else.

**Comment by samyakmaitre** [comment]
I guess you are not working with the latest version, kindly sync your fork and make your changes. Everthing else is fine.

**Comment by samyakmaitre** [comment]
Sync your fork and create new PR, I will merge DW.

**Pull request closed without merging**
