### PR TITLE
navbar :solved the navbar issue to make it sticky

### PR DESCRIPTION
**Pull request by dipeshkumar799**
i have to solved the navbar issue to  make it  sticky position.

https://github.com/user-attachments/assets/fef6ebfb-4581-4ba5-a67e-eb7ed09f4685

@samyakmaitre :pls review my  changeses 
#380

### CODE REVIEW

**Comment by samyakmaitre** [comment]
image

make header and navbar both  sticky

**Comment by samyakmaitre** [comment]
sync and also resolve conflicts

**Review by samyakmaitre — COMMENTED** [review]
Reviewed changes

**Comment by samyakmaitre** [comment]
another PR merged

**Comment by samyakmaitre** [comment]
its showing issue, please sync your fork once

**Comment by dipeshkumar799** [comment]
i  have synced my forked repository please check and merged it. @samyakmaitre

**Review by samyakmaitre — COMMENTED** [review]
changes reviewed

**Comment by samyakmaitre** [comment]
Thank you for your contribution! The merge has been completed successfully, and the labels have been added. I appreciate your efforts, and don't forget to connect with me on GitHub!

Best regards,
Samyak

**Pull request merged**
