### PR TITLE
update the style of movie detail page 

### PR DESCRIPTION
**Pull request by mahaveergurjar**
update the css of movie detail page
fix issue #385 

  old styling
image
image

new styling
image
image

### CODE REVIEW

**Comment by mahaveergurjar** [comment]
If cast image you prefer round then tell me i change into circle

**Comment by samyakmaitre** [comment]
keep them in circle, also sync your fork

**Comment by samyakmaitre** [comment]
Hi there,

Thank you for your interest! The issue has already been assigned to another contributor. We appreciate your eagerness to help and look forward to your contributions in the future. Dont forget to connect on Github....

Best regards,
Samyak

**Comment by mahaveergurjar** [comment]
Ok

**Comment by mahaveergurjar** [comment]
issue fixed review my pr

image

**Comment by samyakmaitre** [comment]
Thank you for your contribution! The merge has been completed successfully, and the labels have been added. I appreciate your efforts, and don't forget to connect with me on GitHub!

Best regards,
Samyak

**Pull request merged**
