### PR TITLE
Header and navbar fixed made them sticky till the end

### LINKED ISSUE #14: Fixing navbar to the top while scrolling
Fixing navbar to the top of screen while scrolling to improve navigation
Screenshot 2024-10-01 213705

### LINKED ISSUE #15: feat : Improving navbar with proper  alignment and content
image
As seen in the above image the **Sign in text is wrapping**  affecting the UI of the website.

Also the **navbar is simple** with **no proper fonts added**

## Suggested changes : 
<ol>
<li>Appropriate padding of navbar</li>
<li>Styling of navbar</li>
<li>Ensure proper fonts for the website</li>
</ol>

### LINKED ISSUE #23: Make navbar sticky

### LINKED ISSUE #35: Improve Footer and Navbar Sections
I'd like to improvements to both the Footer and Navbar sections to enhance usability and design consistency across the site.

Could you please add the "label for level" , "Hacktoberfest-accepted" label and "gssoc-ext" label to the issue .

This will ensure my contributions are counted towards Hacktoberfest.

Screenshot 2024-10-03 113936

Screenshot 2024-10-03 113954

### PR DESCRIPTION
**Pull request by PraveenUppar**
Fixed header and navbar making them sticky for a better user experience

Fixes #35 
Fixes #23
Fixes #14
Fixes #15

Screenshot
Screenshot 2024-10-04 121321

### CODE REVIEW

**Comment by PraveenUppar** [comment]
I checked with running the file no issues were found

**Comment by PraveenUppar** [comment]
Once merge with the main branch and check 
Can you gssoc-ext and hacktoberfest-accepeted label to the pr it would really help me
Thankyou

**Comment by Sourabh782** [comment]
@PraveenUppar why u added my issue?
you cant start working without issue alloting to you

**Comment by samyakmaitre** [comment]
Issue resolved by #9 (raised first)
Kindly do not resolved/copy other contributors issue.

Feel free to collaborate on additional features in the future. Thank you for your cooperation.

**Pull request closed without merging**
