### PR TITLE
Footer fixations

### PR DESCRIPTION
**Pull request by ezDecode**

### CODE REVIEW

**Comment by ezDecode** [comment]
@samyakmaitre Check out this.

**Comment by samyakmaitre** [comment]
Thank you for your contribution! The merge has been completed successfully, and the labels have been added. I appreciate your efforts, and don't forget to connect with me on GitHub!

Best regards,
Samyak

**Comment by ezDecode** [comment]
I want to add some more cards in the home page and make some changes but I don't know how to get started can you please assist me??

**Review by samyakmaitre — COMMENTED** [review]
Changes Reviewed

**Pull request merged**
