### PR TITLE
Add the modification

### PR DESCRIPTION
**Pull request by Dipanita45**
Add or update the CSS properties to make the website eye catching

### CODE REVIEW

**Comment by Dipanita45** [comment]
I had resolved the conflicts @samyakmaitre 
Please review the pull request and label me level 2

**Comment by samyakmaitre** [comment]
please mention visible changes you made

**Comment by Dipanita45** [comment]
Add the  transition effects on the list in navbar as well as in the list,
weight and colour of the text and more etc

**Comment by samyakmaitre** [comment]
image
see this issue

**Comment by Dipanita45** [comment]
Please  label me

**Comment by samyakmaitre** [comment]
I cannot find any remarkable change.

**Comment by Dipanita45** [comment]
Please review and label me I have tried to change the modifications but why
it is not showing 😞

**Pull request closed without merging**
