### PR TITLE
Fix Footer Alignment and Remove underline  from the footer Links!!

### PR DESCRIPTION
**Pull request by ezDecode**
Updated Font-Awesome dependencies, fixed footer alignment, and removed underlines from links.
Issue Raise #186 
Close #206

### CODE REVIEW

**Comment by samyakmaitre** [comment]
resolve conflicts

**Comment by ezDecode** [comment]
image

**Comment by samyakmaitre** [comment]
Kindly sync fork and let me know.

**Comment by ezDecode** [comment]
Hey, @samyakmaitre  Kindly check this **Fix header logo alignment and update footer links #297**

**Comment by samyakmaitre** [comment]
@ezDecode 297 and 206 both are same?

**Comment by ezDecode** [comment]
No, close this and consider the #297

**Comment by samyakmaitre** [comment]
Alright

**Pull request closed without merging**
