### PR TITLE
Created StreamEvents and Plays Page

### LINKED ISSUE #355: No StreamEvents and Plays Page
### Description
We need to add two new components to enhance the functionality of our application: **StreamEvents.js** and **Plays.js**.

### Benefits
Adding these components will improve user engagement and provide a more organized interface for viewing events and plays.

### PR DESCRIPTION
**Pull request by Siddhart2004**
### Description
This pull request introduces two new components: `StreamEvents.js` and `Plays.js`, to enhance the functionality of the application.

### Related Issue
- Fixes #355

### Changes Made
- **StreamEvents.js**: 
  - Displays a list of upcoming stream events, including the event title, date, time, and description.
  - Utilizes a responsive design to ensure proper display on various screen sizes.
  - Includes a navigation bar for easy access to other parts of the application.

- **Plays.js**:
  - Showcases a list of upcoming plays, providing information such as title, date, time, and a brief description.
  - Features a similar responsive layout for consistency across components.
  - Integrates the same navigation bar as the `StreamEvents` component for a seamless user experience.

### CODE REVIEW

**Comment by Siddhart2004** [comment]
@samyakmaitre Check the changes and give me suggestions, also add relevant labels.

**Comment by Siddhart2004** [comment]
@samyakmaitre Check the changes and give me suggestions, also add relevant labels.

**Comment by samyakmaitre** [comment]
Hi there,
I found that StreamEvents.js and Plays.js are just a similar copy of offers.js PFA for reference, I need different UI for each nav options. and therefore cannot merge this PR.

image

**Review by samyakmaitre — COMMENTED** [review]
Changes Reviewed

**Pull request closed without merging**
