### PR TITLE
Update tab title from react app to bookmy show

### LINKED ISSUE #47: Change the tab name from React App to BookmyShow
## Isssue
The existing tab name is React App it can be changed to BookmyShow for better user experience
## Screenshot
Screenshot 2024-10-04 113116

### PR DESCRIPTION
**Pull request by PraveenUppar**
##
Fixed the tab title from React App to BookmyShow 
Fixes #47 

##Screenshot
Screenshot 2024-10-04 114446

### CODE REVIEW

**Comment by PraveenUppar** [comment]
The code has no conflicts with the base branch

**Comment by PraveenUppar** [comment]
I checked with running the file no issues were found

**Comment by PraveenUppar** [comment]
Once merge with the main branch and check 
Can you gssoc-ext and hacktoberfest-accepeted label to the pr it would really help me
Thankyou

**Comment by samyakmaitre** [comment]
Please change the title to EventMint

**Pull request closed without merging**
