### PR TITLE
EM9

### PR DESCRIPTION
**Pull request by Gauravtb2253**
Hello
I have solved EM9 pls check it

Also working on EM8

### CODE REVIEW

**Comment by samyakmaitre** [comment]
WhatsApp Image 2024-10-14 at 15 29 55_a70ad53d

see the alignment and position

**Comment by samyakmaitre** [comment]
image


also remove this changes 
special offers need to be under offer section of nav bar

**Comment by Gauravtb2253** [comment]
pls check I have made changes

**Comment by samyakmaitre** [comment]
still the same

**Comment by Gauravtb2253** [comment]
image

Actually it showing correctly in my laptop

**Comment by samyakmaitre** [comment]
ok work on EM8 here itself

**Comment by Gauravtb2253** [comment]
I have solve EM8 pls check

**Comment by samyakmaitre** [comment]
image
showing 3 colours, change it to single color.

**Comment by Gauravtb2253** [comment]
changed

**Comment by samyakmaitre** [comment]
bro u so fast

**Comment by samyakmaitre** [comment]
Thank you for your contribution! The merge has been completed successfully, and the labels have been added. I appreciate your efforts, and don't forget to connect with me on GitHub!

Best regards,
Samyak

**Comment by samyakmaitre** [comment]
#EM10 added check it

**Comment by Gauravtb2253** [comment]
> Thank you for your contribution! The merge has been completed successfully, and the labels have been added. I appreciate your efforts, and don't forget to connect with me on GitHub!
> 
> Best regards, Samyak

Yes Sure

**Review by samyakmaitre — COMMENTED** [review]
Changes Reviewed

**Pull request merged**
